version: '3.7'

services:
  registry:
    container_name: registry
    image: registry:2
    env_file:
      - .env
    environment:
      - REGISTRY_PROXY_REMOTEURL=${REGISTRY_PROXY_REMOTEURL}
      - REGISTRY_PROXY_USERNAME=${REGISTRY_PROXY_USERNAME}
      - REGISTRY_PROXY_PASSWORD=${REGISTRY_PROXY_PASSWORD}
    ports:
      - "${REGISTRY_PUBLIC_PORT:-5000}:5000"
    volumes:
      - registry_data:/var/lib/registry


  mysql:
    container_name: mysql
    image: mysql:8
    env_file:
    - ./php/.env
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USERNAME}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
    - "${MYSQL_PUBLIC_PORT:-3306}:3306"
    volumes:
    - ./docker/mysql/data:/var/lib/mysql


  php:
    container_name: php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./php:/var/www/html
    depends_on:
      - registry
    expose:
      - 9000


  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./php:/var/www/html
    ports:
      - "${NGINX_PUBLIC_PORT:-80}:80"
    depends_on:
      - php

volumes:
  registry_data:
