version: '3.7'

services:
  registry:
    container_name: registry
    image: registry:2
    env_file:
      - .env
    environment:
      - REGISTRY_PROXY_REMOTEURL=${REGISTRY_PROXY_REMOTEURL}
      - REGISTRY_PROXY_USERNAME=${REGISTRY_PROXY_USERNAME}
      - REGISTRY_PROXY_PASSWORD=${REGISTRY_PROXY_PASSWORD}
    ports:
      - "${REGISTRY_PUBLIC_PORT:-5000}:5000"
    volumes:
      - registry_data:/var/lib/registry

volumes:
  registry_data:
